jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-dependencies-v1-{{ checksum "build.gradle" }}
            - gradle-dependencies-v1-
      - run:
          name: Configurar SDK de Android
          command: |
            # Instalar SDK
      - run:
          name: Compilar APK
          command: ./gradlew clean assembleDebug
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-dependencies-v1-{{ checksum "build.gradle" }}
