version: "v1.0"

name: Android Simple Test Pipeline

agent:
  machine:
    type: e1-standard-2  # Define el tipo de máquina o agente para ejecutar las tareas
    os_image: ubuntu-2004  # Define la imagen del sistema operativo

blocks:
  - name: Setup Android Environment
    task:
      prologue:
        commands:
          - C:\Users\GioMoreno\AndroidStudioProjects\MyHabitrack/app/src/main/res/activity_main_login.xml
      main:
        commands:
          - echo "Comprobando dependencias..."
          - ./gradlew dependencies

  - name: Build Project
    task:
      main:
        commands:
          - echo "Construyendo el proyecto..."
          - ./gradlew assembleDebug

  - name: Run Unit Tests
    task:
      main:
        commands:
          - echo "Ejecutando pruebas unitarias..."
          - ./gradlew test

pipelines:
  default:
    blocks:
      - name: Setup Android Environment
      - name: Build Project
      - name: Run Unit Tests
