version: "v1.0"

name: Android Simple Test Pipeline

agent:
  machine:
    type: e1-standard-2  # Tipo de máquina para el agente
    os_image: ubuntu-20.04  # Imagen del sistema operativo

blocks:
  - name: Setup Android Environment
    task:
      jobs:
        - name: Setup Job
          commands:
            - echo "Configurando el entorno de Android..."
            - curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o android_tools.zip
            - unzip android_tools.zip -d $ANDROID_HOME/cmdline-tools
            - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools
            - yes | sdkmanager --licenses
            - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

  - name: Build Project
    task:
      jobs:
        - name: Build Job
          commands:
            - echo "Construyendo el proyecto..."
            - ./gradlew assembleDebug

  - name: Run Unit Tests
    task:
      jobs:
        - name: Test Job
          commands:
            - echo "Ejecutando pruebas unitarias..."
            - ./gradlew test

pipelines:
  default:
    blocks:
      - name: Setup Android Environment
      - name: Build Project
      - name: Run Unit Tests
